wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.9.16
    cli_version: 0.15.5
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1693927065.570784
    t:
      1:
      - 1
      - 41
      - 55
      2:
      - 1
      - 41
      - 55
      3:
      - 17
      - 23
      - 37
      4: 3.9.16
      5: 0.15.5
      8:
      - 5
num_users:
  desc: null
  value: 50
noniid:
  desc: null
  value: false
class_per_each_client:
  desc: null
  value: 10
selected_idx:
  desc: null
  value: 3
frac:
  desc: null
  value: 0.1
bs:
  desc: null
  value: 64
local_bs:
  desc: null
  value: 64
momentum:
  desc: null
  value: 0
epochs:
  desc: null
  value: 500
local_ep:
  desc: null
  value: 5
num_classes:
  desc: null
  value: 10
lr:
  desc: null
  value: 0.1
weight_decay:
  desc: null
  value: 0
mode:
  desc: null
  value: normal
rs:
  desc: null
  value: 0
model_name:
  desc: null
  value: resnet18
data:
  desc: null
  value: cifar10
device_id:
  desc: null
  value: '0'
learnable_step:
  desc: null
  value: true
run_name:
  desc: null
  value: reduction_resnet18_1
cut_point:
  desc: null
  value: 1
seed:
  desc: null
  value: 123
device:
  desc: null
  value: cuda:0
