wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.9.0
    cli_version: 0.15.10
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1694171895.569209
    t:
      1:
      - 1
      - 41
      - 55
      2:
      - 1
      - 41
      - 55
      3:
      - 17
      - 23
      - 37
      4: 3.9.0
      5: 0.15.10
      8:
      - 5
num_users:
  desc: null
  value: 50
noniid:
  desc: null
  value: false
class_per_each_client:
  desc: null
  value: 10
selected_idx:
  desc: null
  value: 3
frac:
  desc: null
  value: 0.1
bs:
  desc: null
  value: 64
local_bs:
  desc: null
  value: 64
momentum:
  desc: null
  value: 0
epochs:
  desc: null
  value: 500
local_ep:
  desc: null
  value: 5
num_classes:
  desc: null
  value: 10
lr:
  desc: null
  value: 0.1
weight_decay:
  desc: null
  value: 0
mode:
  desc: null
  value: normal
rs:
  desc: null
  value: 0
model_name:
  desc: null
  value: resnet18
data:
  desc: null
  value: cifar10
device_id:
  desc: null
  value: '0'
learnable_step:
  desc: null
  value: true
ps:
  desc: null
  value: []
run_name:
  desc: null
  value: resnet18
cut_point:
  desc: null
  value: []
seed:
  desc: null
  value: 123
T:
  desc: null
  value: 4
device:
  desc: null
  value: cuda:0
cut:
  desc: null
  value:
  - 1
  - 2
  - 3
  - 4
num_models:
  desc: null
  value: 4
